yast/skelcd-control-SLES

control/control.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
https://fate.suse.com/317481 Add 'System Role' capabilities to installer
This needs https://github.com/yast/yast-installation-control/pull/19 to pass build-time schema validation.
=> System Role (FATE#317481)

control/control.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
https://fate.suse.com/319716
https://trello.com/c/T49hdvDd/498-5-self-update-change-dud-support-to-rpmmd-repository-with-rpms
https://github.com/yast/yast-installation/pull/356
The self-update client should be invoked from control file.
=> Invoke inst_update_installer client after system_analysis

control/control.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
- Added SSH keys import section to the proposal. See https://github.com/yast/yast-installation/pull/374
- Remove not longer necessary items from the `copy_to_system` section
- SSH host keys no longer necessary. See https://build.opensuse.org/request/show/396066
- Users database not longer necessary for user import. See https://build.opensuse.org/request/show/393918
=> Fate#319624

package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
Port of https://github.com/yast/skelcd-control-openSUSE/pull/45.
=> Include the Ruby debugger (byebug) in the inst-sys (FATE#318421)

control/control.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
Reference: https://bugzilla.suse.com/show_bug.cgi?id=986640
Before this fix: even for a [KVM server role](https://github.com/yast/yast-installation/wiki/System-Role), desktop related patterns are included; the systemd target is graphical:
With this fix, only the 3 patterns explicitly intended for the KVM role are selected, and no desktop related patterns. Accordingly, the system boots to text mode:
Implementation: Override `optional_default_patterns` and `default_desktop` with empty values.
Note the use of a fancy XML empty string (with CDATA) so that Yast::XML includes the empty string in the resulting hash. A plain `<default_desktop/>` would omit the `"default_desktop"` key entirely.
=> Do not install desktop patterns for KVM and XEN system roles

package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
Install and enable xrdp by default ([FATE#320363](https://fate.suse.com/320363))
yast2-rdp will be only enabled in the proposal of SLES_SAP which has its own control.xml
This supersedes #66 which was submitted to SLES before merging. @varkoly please do not do this!
See also the fat warning in the spec file:
```
######################################################################
#
#
#
######################################################################
```
=> Install and enable xrdp by default (FATE#320363)

control/control.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
Remove some files from the inst-sys to have more free RAM on low memory systems.
This PR activates the cleaner (https://github.com/yast/yast-installation/pull/407) in the installation/upgrade workflow.
- Version updated to 12.2.0 (to match SP2, it seems we forgot to bump the minor version in SP1...)
The cleaner is called at the initial stage when the inst-sys is running in memory:
- Initial installation
- Upgrade
- Autoinstallation
- Autoupgrade
=> Run the Inst-sys clean up (bsc#974601)

control/control.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
- The initial (manual) installation
- The initial (manual) upgrade
- AutoYaST installation
- AutoYaST upgrade
=> Move the self update step

control/control.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
https://trello.com/c/JdvwBp5G/457-5-microos-12-sp2-move-default-subvolumes-to-control-file
Notice that right now Travis fails because it doesn't have the new schema yet. That is expected.
I tested this control.xml in my VM. It also validates against the updated schema.
For comparison, the fallback list (taken from the old code), which is the same as the subvolumes in this PR, is here:
https://github.com/yast/yast-storage/blob/SLE-12-SP2-CASP/src/lib/storage/subvol.rb#L36
https://github.com/yast/yast-storage/blob/SLE-12-SP2-CASP/src/lib/storage/subvol.rb#L165
=> Added subvolumes to control.xml (fate#321737) 

.travis.yml, Rakefile
This reverts commit 6190a0160839deb998acefa458a1284b5eb48600 (PR #77).
The rake check:syntax is also called at Jenkins, it does not work
there and breaks the package submission.
=> Revert "Improve the Travis check"

control/installation.SLES.xml, package/skelcd-control-SLES.changes
no need to submit now, with next change is sufficient, that's why no version bump
=> removed minimal_base pattern from minimal role (bsc#1064135)

control/installation.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
Signed-off-by: Karol Mroz <kmroz@suse.de>
=> /var/lib/ceph as btrfs subvolume with CoW disabled (bsc#1013011)

control/installation.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
- Display the license dialog just after selecting the root partition
- See https://bugzilla.suse.com/show_bug.cgi?id=1069124
- 15.0.15
- :100: :tada:
=> Display the product license at upgrade (bsc#1069124)

control/control.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
- https://trello.com/c/eLMiRWmH/1350-2-bug-1078991-l3-autoyast-unable-to-find-disk-with-option-withfcoe
=> Add 'fcoe-client' to the list of clonable modules

.gitignore, .travis.sh, .travis.yml, Dockerfile, control/control.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
- [Trello Card](https://trello.com/c/eLMiRWmH/1350-2-bug-1078991-l3-autoyast-unable-to-find-disk-with-option-withfcoe)
=> Add 'fcoe-client' to the list of clonable modules (SP2)

control/control.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
These regexp will cause update settings for migration being changed for
matching products.
The additions will keep SLE-HPC in sync with SLES (bsc#1094166).
Version 12.4.0
Signed-off-by: Egbert Eich <eich@suse.com>
=> Add regexps to match "SUSE Linux Enterprise High Performance Computing"

control/control.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
As part of the `Optimize /var for Btrfs use` epic, the _/var/log_ subvolume will be configured as **NoCOW**.
- https://trello.com/c/l8VQI362 
---
Tested manually via driver update.
<details>
<summary>Click to show/hide screenshots</summary>
---
</details>
=> Set NoCOW for /var/log Btrfs subvolume

control/installation.SLES.xml, package/skelcd-control-SLES.changes
During the review meeting it was agreed to add a comment directly to the control file to explain the default value of `adjust_by_ram` setting in s390 for swap.
Related to https://trello.com/c/xNInsz6m/1088-1-storage-enlarge-to-ram-set-to-false-by-default-for-s390
=> Add comment about s390

control/installation.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
- Skip the registration on the new online medium (the system has been already registered                     at this point) and offline medium (registration is not required there).
- The registration step is only kept for the backward compatibility for the old Installer medium to not break the current openQA tests.
- It can be removed completely once the old Installer and Packages DVD are dropped.
- Related to https://github.com/yast/yast-registration/pull/444
- 15.2.0
=> Skip the registration step (jsc#SLE-7214)

control/control.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
- https://bugzilla.suse.com/show_bug.cgi?id=1152275
- 12.5.1
- (We should really avoid hardcoding the version... :worried: )
=> Fixed the default self_update URL for SP5 (bsc#1152275)

control/installation.SLES.xml, package/skelcd-control-SLES.changes, package/skelcd-control-SLES.spec
- See [bsc#1171814](https://bugzilla.suse.com/show_bug.cgi?id=1171814)
- Added new defaults for the Full installation medium
- The original feature request [SLE-8040](https://jira.suse.com/browse/SLE-8040) requested only the Basesystem module... :angry:  
- 15.2.2
=> Preselect the Basesystem and Server Applications modules (bsc#1171814)
